version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:2.255
    ports:
    - "9080:8080"
    volumes:
    - jenkins_homedir:/var/jenkins_home
    restart: unless-stopped
  mails:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
    - "8025:8025"
volumes:
  jenkins_homedir: